name: run-tests

on:
  pull_request:
    branches:
      - main
      
permissions:
  contents: read         # Read repository contents (default)
  pull-requests: write   # Write access to pull requests
  actions: read          # Read access to actions
  statuses: write        # Write access to commit statuses
  
jobs:
  build:
    name: unit-tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y cmake g++ libgtest-dev

    - name: Configure and Build
      run: |
        cmake -S . -B build
        cmake --build build

    - name: Run Tests
      run: ./build/test_add

